export type ReplyDoneSoundTone =
  | "glass"
  | "marimba"
  | "bell"
  | "crystal"
  | "harp"
  | "wood"
  | "synth"
  | "orb";
export type ReplyDoneSoundSource = "tone" | "custom";

export type UiSettings = {
  fontFamily: string;
  fontSize: number;
  lineHeight: number;
  contentWidth: number;
  sidebarFontSize: number;
  sidebarWidth: number;
  modelBadgeScale: number;
  composerActionScale: number;
  footerStatsFontSize: number;
  autoScrollAssistantResponses: boolean;
  showMessageTimestamp: boolean;
  messageTimestampFontSize: number;
  playReplyDoneSound: boolean;
  playReplyDoneSoundVolume: number;
  playReplyDoneSoundTone: ReplyDoneSoundTone;
  playReplyDoneSoundSource: ReplyDoneSoundSource;
  playReplyDoneSoundCustomAudioDataUrl: string;
  playReplyDoneSoundCustomAudioName: string;
  showToolActivity: boolean;
  toolCallFontSize: number;
  chatBubbleRadius: number;
  messageGap: number;
  panelOpacity: number;
  backgroundPatternStrength: number;
  accentColor: string;
  accentSoftColor: string;
  userBubbleColor: string;
  assistantBubbleColor: string;
  markdownHeadingColor: string;
  markdownLinkColor: string;
  markdownBoldColor: string;
  markdownItalicColor: string;
  markdownCodeBg: string;
  markdownCodeText: string;
  markdownQuoteBg: string;
  markdownQuoteBorderColor: string;
  enableAnimations: boolean;
};

export const DEFAULT_UI_SETTINGS: UiSettings = {
  fontFamily: "Manrope",
  fontSize: 16,
  lineHeight: 1.62,
  contentWidth: 900,
  sidebarFontSize: 13,
  sidebarWidth: 300,
  modelBadgeScale: 1,
  composerActionScale: 1,
  footerStatsFontSize: 12,
  autoScrollAssistantResponses: true,
  showMessageTimestamp: true,
  messageTimestampFontSize: 11,
  playReplyDoneSound: true,
  playReplyDoneSoundVolume: 58,
  playReplyDoneSoundTone: "glass",
  playReplyDoneSoundSource: "tone",
  playReplyDoneSoundCustomAudioDataUrl: "",
  playReplyDoneSoundCustomAudioName: "",
  showToolActivity: true,
  toolCallFontSize: 12,
  chatBubbleRadius: 12,
  messageGap: 14,
  panelOpacity: 100,
  backgroundPatternStrength: 10,
  accentColor: "#18181b",
  accentSoftColor: "#f4f4f5",
  userBubbleColor: "#f4f4f5",
  assistantBubbleColor: "#ffffff",
  markdownHeadingColor: "#18181b",
  markdownLinkColor: "#18181b",
  markdownBoldColor: "#111827",
  markdownItalicColor: "#3f3f46",
  markdownCodeBg: "#f4f4f5",
  markdownCodeText: "#18181b",
  markdownQuoteBg: "#fafafa",
  markdownQuoteBorderColor: "#d4d4d8",
  enableAnimations: true,
};
